# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(default='apellido', max_length=255),
            preserve_default=False,
        ),
    ]
