# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20171029_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.CharField(default='20', max_length=3),
            preserve_default=False,
        ),
    ]
